### ISSUE TITLE
Add ability to customize pip packages installed (e.g. `pip3 install pyspf`)

### ISSUE THREAD

**Issue by niftylettuce** [Oefenweb/ansible-pip#10]
It would be awesome to have something like:

```yml
---
- hosts: all
  become: true
  vars:
    pip_python_version: 3
    pip_packages:
      - pyspf
      - dnspython
      - dkimpy
  roles:
  - role: pip
```
